version: 2

sources:
  - name: airbnb # nazwa modelu/bazy danych
    schema: raw  # nazwa schemy
    tables: 
      - name: listings #nazwa tabeli w bazie danych bez podania schematu
        description: Tabela zawierajaca wynajmowane miejsca
        columns:
          - name: room_type
            data_tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
          - name: price
            data_tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\$[0-9][0-9\\.]+$"   # ^ - tekst zaczyna się od znaku po ^, $ znak w regex ma spejalne znaczenie więc trzeba go poprzedzić \ ale w YAML żeby był znak \ musimy uzyć \\, 

      - name: hosts
        description: Tabela zawierające dane gospodarzy
      - name: reviews 
        decription: Tabela zawierająca dane ocen lokali
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: date 
